package uk.ac.ebi.extended.serialization.constants

object ExtSerializationFields {
    const val ACC_NO = "accNo"
    const val ATTRIBUTES = "attributes"
    const val EXT_TYPE = "extType"
    const val FILE = "file"
    const val FILES = "files"
    const val FILES_URL = "filesUrl"
    const val FILE_LIST = "fileList"
    const val LINKS = "links"
    const val SECTIONS = "sections"
    const val TYPE = "type"
    const val URL = "url"

    // Ext Files Fields
    const val FILE_NAME = "fileName"
    const val FILE_FILEPATH = "filePath"
    const val FILE_REL_PATH = "relPath"
    const val FILE_FULL_PATH = "fullPath"
    const val FILE_TYPE = "type"
    const val FILE_FIRE_ID = "fireId"
    const val FILE_FIRE_PUBLISHED = "published"
    const val FILE_FIRE_PATH = "firePath"
    const val FILE_SIZE = "size"
    const val FILE_MD5 = "md5"

    // Ext Attributes Fields
    const val ATTR_NAME = "name"
    const val ATTR_VALUE = "value"
    const val ATTR_REFERENCE = "reference"
    const val ATTR_NAME_ATTRS = "nameAttrs"
    const val ATTR_VAL_ATTRS = "valueAttrs"

    // Ext Submission Fields
    var VERSION = "version"
    var SCHEMA_VERSION = "schemaVersion"
    const val OWNER = "owner"
    const val SUBMITTER = "submitter"
    const val TITLE = "title"
    const val DOI = "doi"
    const val METHOD = "method"
    const val REL_PATH = "relPath"
    const val ROOT_PATH = "rootPath"
    const val RELEASED = "released"
    const val SECRET_KEY = "secretKey"
    const val RELEASE_TIME = "releaseTime"
    const val MOD_TIME = "modificationTime"
    const val CREATION_TIME = "creationTime"
    const val SECTION = "section"
    const val TAGS = "tags"
    const val COLLECTIONS = "collections"
    const val STATS = "stats"
    const val ACCESS_TAGS = "accessTags"
    const val PAGE_TAB_FILES = "pageTabFiles"
    const val STORAGE_MODE = "storageMode"
}
