logging:
  level:
    root: info

spring:
  datasource:
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false


  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

  mvc:
    async:
      request-timeout: -1

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

app:
  submissionPath:
  ftpPath:
  tempDirPath:
  requestFilesPath:
  instanceBaseUrl: http://localhost:8080
  consumers: 1
  maxConsumers: 2
  fire:
    host:
    username:
    password:
    version: v1.1
    retry:
      maxAttempts: 20
      initialInterval: 5
      multiplier: 2.0
      maxInterval: 1
  security:
    tokenHash: biostd-test
    environment: TEST
    requireActivation: false
    filesProperties:
      defaultMode: NFS
      filesDirPath:
      magicDirPath:
      ftpUser:
      ftpPassword:
      ftpUrl:
      ftpPort:
  validator:
    euToxRiskValidationApi: # EU-ToxRisk validation API
  featureFlags:
    tsvPagetabExtension: true
  notifications:
    requestQueue: submission-request-submitter-queue # queue used to handle request stages
    requestRoutingKey: bio.submission.requested # request messages routing key


