spring:
  datasource:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

app:
  basepath:
  tempDirPath:
  security:
    tokenHash: biostd-test
    environment: TEST
    filesDirPath:
    requireActivation: false
  notifications:
    smtp:
