INSERT INTO User (
  activationKey,
  active,
  auxProfileInfo,
  email,
  fullName,
  keyTime,
  login,
  passwordDigest,
  secret,
  superuser,
  ssoSubject,
  notificationsEnabled)
VALUES (null, false, null, null, 'Anonymous user', 0, '@Guest', null, null, false, null, false),
       (null, false, null, null, 'Represents system owned objects', 0, '@System', null, null, false, null, false),
       (null, false, null, 'default_user@ebi.ac.uk', 'Default User', 0, '@Default', null, null, false, null, false),
       (null,
        true,
        null,
        'admin_user@ebi.ac.uk',
        'Admin User',
        0,
        'admin_user',
        X'7C4A8D09CA3762AF61E59520943DC26494F8941B',
        '69214a2f-f80b-4f33-86b7-26d3bd0453aa',
        true,
        null,
        false);
