image: gradle:6.5.1-jdk8
services:
  - docker:mydind
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
include:
  - local: '/ci/submitter.yml'
  - local: '/ci/pmc-processor.yml'
  - local: '/ci/submission-releaser.yml'
  - local: '/ci/scheduler.yml'
  - local: '/ci/bio-admin.yml'
  - local: '/ci/bio-commandline.yml'
  - local: '/ci/submission-handlers.yml'

stages:
  - build-test
  - build-artifact
  - auto-deploy-dev-submitter
  - auto-deploy-dev-handlers
  - deploy-dev-submitter
  - deploy-beta-submitter
  - deploy-prod-submitter
  - deploy-dev-pmc
  - deploy-beta-pmc
  - deploy-prod-pmc
  - deploy-dev-releaser-task
  - deploy-beta-releaser-task
  - deploy-prod-releaser-task
  - deploy-dev-scheduler
  - deploy-beta-scheduler
  - deploy-prod-scheduler
  - deploy-bio-admin
  - deploy-bio-commandline
  - deploy-dev-handlers
  - deploy-beta-handlers
  - deploy-prod-handlers

build-test:
  stage: build-test
  script: gradle clean build test buildArtifacts
  artifacts:
    when: always
    reports:
      junit: submission/persistence-mongo/build/test-results/test/**/TEST-*.xml

