image: gradle:6.0-jdk8
include:
  - local: '/ci/submitter.yml'
  - local: '/ci/pmc-processor.yml'
  - local: '/ci/scheduler.yml'
  - local: '/ci/bio-admin.yml'
  - local: '/ci/bio-commandline.yml'
  - local: '/ci/submission-handlers.yml'

stages:
  - build-test
  - build-artifact
  - auto-deploy-dev-submitter
  - auto-deploy-dev-handlers
  - deploy-dev-submitter
  - deploy-beta-submitter
  - deploy-prod-submitter
  - deploy-dev-pmc
  - deploy-beta-pmc
  - deploy-prod-pmc
  - deploy-dev-scheduler
  - deploy-beta-scheduler
  - deploy-prod-scheduler
  - deploy-bio-admin
  - deploy-bio-commandline
  - deploy-dev-handlers
  - deploy-beta-handlers
  - deploy-prod-handlers

build-test:
  stage: build-test
  script: gradle clean build test buildArtifacts
  artifacts:
    paths:
      - bio-admin/build/libs/bio-admin-1.0.0.jar
      - client/bio-commandline/build/libs/PTSubmit-2.0.jar
      - scheduler/scheduler/build/libs/scheduler-1.0.0.jar
      - scheduler/pmc-processor-task/build/libs/pmc-processor-task-1.0.0.jar
      - submission/submission-webapp/build/libs/submission-webapp-1.0.0.jar
      - submission/submission-handlers/build/libs/submission-handlers-1.0.0.jar
