image: gradle:5.4.1-jdk8
include:
  - local: '/ci/submitter.yml'
  - local: '/ci/pmc-processor.yml'
  - local: '/ci/scheduler.yml'

stages:
  - clean
  - compile
  - test
  - build
  - deploy-dev-submitter
  - deploy-beta-submitter
  - deploy-prod-submitter
  - deploy-dev-pmc
  - deploy-beta-pmc
  - deploy-prod-pmc
  - deploy-dev-scheduler
  - deploy-beta-scheduler
  - deploy-prod-scheduler

clean-job:
  stage: clean
  script: gradle clean

compile-job:
  stage: compile
  script: gradle build -x test

test-job:
  stage: test
  script: gradle test

