image: gradle:8.7-jdk17
services:
  - docker:dind
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

include:
  - local: '/ci/docker.yml'
  - local: '/ci/jobs.yml'

stages:
  - build-test
  - nfs-itest
  - fire-itest
  - fire-caos-itest
  - auto-deploy-dev
  - auto-deploy-beta
  - auto-deploy-prod
  - deploy-dev
  - deploy-beta
  - deploy-prod
  - build-fat-jar
  - build-push-docker-image

build-test:
  stage: build-test
  script:
    - apt-get update && apt-get install -y rsync
    - gradle submission:submission-webapp:itest --tests ac.uk.ebi.biostd.itest.test.user.UserAdminApiTest

nfs-itest:
  needs: [ "build-test" ]
  stage: nfs-itest
  script: gradle :submission:submission-webapp:itest -PenableFire=false --rerun-tasks

fire-itest:
  needs: [ "nfs-itest" ]
  stage: fire-itest
  script: gradle :submission:submission-webapp:itest -PenableFire=true --rerun-tasks
  variables:
    ITEST_FIXED_DELAY: "50"

fire-caos-itest:
  needs: [ "fire-itest" ]
  stage: fire-caos-itest
  script: gradle :submission:submission-webapp:itest -PenableFire=true --rerun-tasks
  variables:
    ITEST_FAIL_FACTOR: "8"
