image: gradle:6.5.1-jdk8
services:
  - docker:dind
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

include:
  - local: '/ci/submitter.yml'
  - local: '/ci/pmc-processor.yml'
  - local: '/ci/exporter.yml'
  - local: '/ci/submission-releaser.yml'
  - local: '/ci/scheduler.yml'
  - local: '/ci/bio-admin.yml'
  - local: '/ci/bio-commandline.yml'
  - local: '/ci/submission-handlers.yml'

stages:
  - build-test
  - integration-test
  - auto-deploy-dev-submitter
  - auto-deploy-dev-handlers
  - deploy-dev-submitter
  - deploy-beta-submitter
  - deploy-prod-submitter
  - deploy-dev-pmc
  - deploy-beta-pmc
  - deploy-prod-pmc
  - deploy-dev-exporter-task
  - deploy-beta-exporter-task
  - deploy-prod-exporter-task
  - deploy-dev-releaser-task
  - deploy-beta-releaser-task
  - deploy-prod-releaser-task
  - deploy-dev-scheduler
  - deploy-beta-scheduler
  - deploy-prod-scheduler
  - deploy-bio-admin
  - deploy-bio-commandline
  - deploy-dev-handlers
  - deploy-beta-handlers
  - deploy-prod-handlers

build-test:
  stage: build-test
  script: gradle clean build test buildArtifacts --stacktrace -x itest
  artifacts:
    paths:
      - bio-admin/build/libs/bio-admin-1.0.0.jar
      - client/bio-commandline/build/libs/BioStudiesCLI-2.0.jar
      - scheduler/scheduler/build/libs/scheduler-1.0.0.jar
      - scheduler/pmc-processor-task/build/libs/pmc-processor-task-1.0.0.jar
      - scheduler/exporter-task/build/libs/exporter-task-1.0.0.jar
      - scheduler/submission-releaser-task/build/libs/submission-releaser-task-1.0.0.jar
      - submission/submission-webapp/build/libs/submission-webapp-1.0.0.jar
      - submission/submission-handlers/build/libs/submission-handlers-1.0.0.jar

mysql-itest:
  stage: integration-test
  script: gradle clean :submission:submission-webapp:itest -Pitest.mode=mysql --rerun-tasks --stacktrace

mongo-itest:
  stage: integration-test
  script: gradle clean :submission:submission-webapp:itest -Pitest.mode=mongo --rerun-tasks --stacktrace