spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BioStudiesDev
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

app:
  basepath: /Users/jhoanmanuelms/EBI/nfs
  tempDirPath: /Users/jhoanmanuelms/EBI/nfs/tmp
  security:
    tokenHash: bio-local
    filesDirPath: /Users/jhoanmanuelms/EBI/nfs/dropbox
    environment: LOCAL
    requireActivation: false
  notifications:
    smtp: smtp.ebi.ac.uk
