spring:
  datasource:
    url: # Database connection URL
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

app:
  basepath: # Path to the folder that will be used as storage
  security:
    tokenHash: # Token used for hash authentication
    environment: # Current application execution environment
    requiresActivation: # Indicates whether or not, new user need activation before being used
