spring:
  application:
    name: Submitter-Dev

  boot:
    admin:
      client:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/BioStudies?useSSL=false
    username: mysql
    password: mysql123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 15
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

rabbitmq:
  host: localhost
  username: guest
  password: guest
  port: 5672

servlet:
  multipart:
    max-file-size: 20GB
    max-request-size: 20GB
    location: ${app.tempDirPath}

logging:
  file:
    max-history: 7
    name: /home/jcrada/Systems/Bio-Local/logs/application_logs.txt

app:
  submissionPath: /home/jcrada/Systems/Bio-Local/submissions
  ftpPath: /home/jcrada/Systems/Bio-Local/ftp
  tempDirPath: /home/jcrada/Systems/Bio-Local/temp
  instanceBaseUrl: http://localhost:8080
  security:
    environment: DEV
    captchaKey: # Captcha validation token
    checkCaptcha: false
    tokenHash: 123-4-567
    filesDirPath: /home/jcrada/Systems/Bio-Local/files
    magicDirPath: /home/jcrada/Systems/Bio-Local/links
    requireActivation: false
  fire:
    host: # FIRE host
    username: # FIRE user
    password: # FIRE password
  notifications:
    smtp: smtp.ebi.ac.uk
    uiUrl: # The BioStudies UI url
  persistence:
    enabledMongo: true
    connection: "mongodb://mongo:mongo@localhost:27017"
