spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  boot:
    admin:
      client:
        url: http://biostudy-prod.ebi.ac.uk:8590
        enabled: false

  data:
    mongodb:
      database: biostudies-dev
      uri: mongodb://root:admin@localhost:27017

  datasource:
    url: jdbc:mysql://localhost:3306/BioStudiesDev
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: localhost
    username: manager
    password: manager-local
    port: 5672

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
      location: ${app.tempDirPath}

logging:
  file:
    max-history: 7
    name: logs/application_logs.txt

app:
  submissionPath: /Users/jhoanmanuelms/EBI/nfs/submission
  ftpPath: /Users/jhoanmanuelms/EBI/nfs/submission/ftp
  tempDirPath: /Users/jhoanmanuelms/EBI/nfs/tmp
  instanceBaseUrl: http://localhost:8080
  fire:
    host: https://hh.fire-test.sdo.ebi.ac.uk
    username: biostudies-test-user1
    password: zRC%6"E2$'u.
  security:
    captchaKey: # Captcha validation token
    checkCaptcha: false
    tokenHash: bio-local
    filesDirPath: /Users/jhoanmanuelms/EBI/nfs/dropbox
    magicDirPath: /Users/jhoanmanuelms/EBI/nfs/magic
    environment: LOCAL
    requireActivation: false
    instanceKeys:
      dev: # Instance key for the submission tool DEV environment
      beta: # Instance key for the submission tool BETA environment
      prod: # Instance key for the submission tool PROD environment
  persistence:
    enableMongo: true
    enableFire: true
  mongo:
    execute-migrations: true
    migration-package: ac.uk.ebi.biostd.persistence.doc.migrations
  validator:
    euToxRiskValidationApi: # EU-ToxRisk validation API
