spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BioStudiesDev
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  data:
    mongodb:
      database: biostudies-dev
      uri: mongodb://root:admin@localhost:27017

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: localhost
    username: manager
    password: manager-local
    port: 5672

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

app:
  submissionPath: # Absolute path to the folder to be used as submission storage
  ftpPath: # Absolute path to the folder to be used ftp hardlinks
  tempDirPath: # Absolute path of the temp folder to store files
  requestFilesPath: # Base directory absolute path where request file list are stored.
  fireTempDirPath: # Absolute path of the temp folder for FIRE storage
  instanceBaseUrl: http://localhost:8080
  fire:
    host: # FIRE host
    username: # FIRE user
    password: # FIRE password
  security:
    captchaKey: # Captcha validation token. Not required for local environment
    checkCaptcha: false
    tokenHash: bio-local
    filesDirPath: # Absolute path to the folder to be used for the user/groups files
    magicDirPath: # Absolute path to the folder to be used for the user/groups magic folders links
    environment: LOCAL
    requireActivation: false
  persistence:
    enableMongo: false
