spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BioStudiesDev
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: localhost
    username: manager
    password: manager-local
    port: 5672

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

app:
  basepath: # Absolute path to the folder to be used as storage
  tempDirPath: # Absolute of the temp folder to store files
  instanceBaseUrl: http://localhost:8080
  security:
    captchaKey: # Captcha validation token. Not required for local environment
    checkCaptcha: false
    tokenHash: bio-local
    filesDirPath: # Absolute path to the folder to be used for the user/groups files
    environment: LOCAL
    requireActivation: false
  notifications:
    smtp: smtp.ebi.ac.uk
    uiUrl: # The BioStudies UI url
    rt:
      host: # RT server host. Not required for local environment
      queue: # Queue used for RT notifications. Not required for local environment
      user: # RT user. Not required for local environment
      password: # RT password. Not required for local environment
