spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BioStudiesDev
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

app:
  basepath: # Path to the folder to be used as storage
  filesDirPath: # Path to the folder to be used for the user/groups files
  tmpDirPath: # Absolute of the temp folder to store files
  security:
    tokenHash: bio-local
    environment: LOCAL
    requireActivation: false
