spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  boot:
    admin:
      client:
        url: http://biostudy-prod.ebi.ac.uk:8590
        enabled: false

  data:
    mongodb:
      database: #Mongo Database Name
      uri: # Mongo Database connection URL

  datasource:
    url: # MySQL Database connection URL
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: # RabbitMQ host
    username: # RabbitMQ user
    password: # RabbitMQ password
    port: # RabbitMQ port

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
      location: ${app.tempDirPath}

logging:
  file:
    max-history: 7
    name: logs/application_logs.txt

app:
  submissionPath: # Absolute path to the folder to be used as submission storage
  ftpPath: # Absolute path to the folder to be used ftp hardlinks
  tempDirPath: # Absolute of the temp folder to store files
  instanceBaseUrl: # Instance base url e.g. http://server.ebi.ac.uk:5541
  fire:
    host: # FIRE host
    username: # FIRE user
    password: # FIRE password
  security:
    captchaKey: # Captcha validation token
    checkCaptcha: false
    tokenHash: # Token used for hash authentication
    filesDirPath: # Absolute path to the folder to be used for the user/groups files
    magicDirPath: #  Absolute path to create user magic folder for dropbox simple access
    environment: # Current application execution environment
    requireActivation: # Indicates whether or not, new user need activation before being used
  persistence:
    enableMongo: false
    connection: # Mongo database connection string

