spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration

  mvc:
    async:
      request-timeout: -1

  data:
    mongodb:
      database: # Mongo Database Name
      uri: # Mongo Database connection URL

  datasource:
    url: # MySQL Database connection URL
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: # RabbitMQ host
    username: # RabbitMQ user
    password: # RabbitMQ password
    port: # RabbitMQ port
    listener:
      direct:
        prefetch: 25
      simple:
        prefetch: 25

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
      location: ${app.tempDirPath}

server:
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

logging:
  file:
    name: logs/application_logs.txt
  level:
    org.springframework.data.mongodb.core.convert.QueryMapper: ERROR # Disable to avoid mapping log population.

app:
  processId: # Id to register the submission task
  retrySubmission: # Boolean flag to enable/disable automatic retrying of staled submissions
  asyncMode: false # Boolean flag to enable/disable the async submission validation
  enablePropertiesLog: # Boolean flag to enable/disable displaying the application properties on start
  consumers: # Number of processing queue consumers.
  maxConsumers: # Max number of processing queue consumers.
  instanceBaseUrl: # Instance base url e.g. http://server.ebi.ac.uk:5541
  #subBasePath: # Allows to allocate submissions under different base path. Commented to avoid empty string binding.
  submissionTask:
    enabled: # Whether the submission tasks should be executed in the cluster
    jarLocation: # the submitter task jar location.
    javaLocation: # The path to the java installation
    javaMemoryAllocation: # JVM memory allocation in GB
    tmpFilesDirPath: # Path to place the temporary files
    singleJobMode: # Whether to execute all submission in a single cluster job
    configFilePath: # the submitter task application.yml file location.
    taskMemoryMgb: # Amount of memory (in MB) to be allocated for the submission processing tasks
    taskCores: # Number of cores to be allocated for the submission processing tasks
    taskMinutes: # Maximum number of minutes to execute the submission processing tasks
  cluster:
    enabled: # Whether the cluster jobs should be triggered remotely
    default: # Default cluster mode. Valid values: LSF | SLURM
    user: # cluster user
    key: # cluster ssh key path.
    lsfServer:  # LSF cluster sever
    slurmServer:  # SLURM cluster sever
    logsPath: # path to place the logs of the dispatched jobs
    wrapperPath: # path to place the command wrapper script
  fire:
    host: # FIRE host
    username: # FIRE user
    password: # FIRE password
    version: # FIRE version
    tempDirPath: # Absolute path to the temp folder for FIRE storage
    s3:
      accessKey: # FIRE s3 access key
      secretKey: # FIRE s3 access key
      region: # Fire s3 region
      endpoint: # Fire s3 region
      bucket: # Fire s3 region
    retry:
      maxAttempts: # Maximum retry attempts
      initialInterval: # Initial waiting interval time in ms
      multiplier: # Multiplier for the waiting interval
      maxInterval: # Maximum interval duration
  security:
    captchaKey: # Captcha validation token
    checkCaptcha: # Boolean flag to enable/disable captcha key checking
    tokenHash: # Token used for hash authentication
    environment: # Current application execution environment
    requireActivation: # Indicates whether a new user need activation before being used
    preventFileDeletion: # Indicates whether to prevent public submission non pagetab file delitions
    instanceKeys:
      dev: # Instance key for the submission tool DEV environment
      beta: # Instance key for the submission tool BETA environment
      prod: # Instance key for the submission tool PROD environment
    filesProperties:
      defaultMode: # The default mode to create user folder. Valid values are: NFS, FTP
      filesDirPath: # Absolute path to the folder to be used for the user/groups files
      magicDirPath: # Absolute path to create user magic folder for dropbox simple access
      userFtpDirPath: # Absolute path of folder where FTP in is mounted on NFS.
      userFtpRootPath: # Root path for user files on FTP
      ftpIn:
        ftpDirPath: # Absolute path of the FTP-OUT folder in NFS
        ftpUser: # FTP user
        ftpPassword: # FTP password
        ftpUrl: # FTP url without port
        ftpPort: # FTP port
        defaultTimeout: # FTP connection pool default timeout
        connectionTimeout: # FTP connection pool connection timeout
        retry:
          maxAttempts: # Maximum retry attempts
          initialInterval: # Initial waiting interval time in ms
          multiplier: # Multiplier for the waiting interval
          maxInterval: # Maximum interval duration
      ftpOut:
        ftpDirPath: # Absolute path of the FTP-IN folder in NFS
        ftpUser: # FTP user
        ftpPassword: # FTP password
        ftpUrl: # FTP url without port
        ftpPort: # FTP port
        defaultTimeout: # FTP connection pool default timeout
        connectionTimeout: # FTP connection pool connection timeout
        retry:
          maxAttempts: # Maximum retry attempts
          initialInterval: # Initial waiting interval time in ms
          multiplier: # Multiplier for the waiting interval
          maxInterval: # Maximum interval duration
  persistence:
    enableFire: # Boolean flag to indicate whether the files are stored on FIRE if true or NFS if false
    concurrency: # Number of files processed concurrently
    includeSecretKey: # Boolean flag to indicate whether the secret key should be added to the private submission path
    nfsReleaseMode: # Method used to release files for NFS submissions. Valid values are: MOVE, HARD_LINKS

    pageTabFallbackPath: # NFS path where the submission pagetab fallback files are generated.
    privateSubmissionsPath: # Absolute path to the folder to be used as storage for private submissions
    privateSubmissionFtpOutPath: # Relative ftp path to the folder to be used as storage for private submissions
    publicSubmissionsPath: # Absolute path to the folder to be used as storage for public submissions

    requestFilesPath: # Absolute path to the folder where request files are stored
    tempDirPath: # Absolute path to the folder used to store http temporary files
  mongo:
    execute-migrations: # Boolean flag to enable/disable the execution of mongo migrations
    migration-package: # Mongo migrations package
  validator:
    euToxRiskValidationApi: # EU-ToxRisk validation API
  notifications:
    requestQueue: # Queue used to handle request stages
    requestRoutingKey: # Submission request messages routing key
    errorNotificationsEnabled: # Boolean flag to enable/disable the Slack error notifications
  doi:
    endpoint: # DOI registration endpoint
    uiUrl: # The BioStudies UI URL which will be associated to the DOI record
    email: # E-Mail to get the DOI processing notifications
    user: # User for the DOI service
    password: # Password for the DOI service
