spring:
  application:
    name: Submitter-Dev

  boot:
    admin:
      client:
        enabled: false

  datasource:
    url: jdbc:mysql://mysql-fg-biostudy-dev.ebi.ac.uk:4639/biostd_dev?useUnicode=true&characterEncoding=utf-8
    username: biostd_dev
    password: biostd_dev
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 15

  jpa:
    show-sql: false

  rabbitmq:
    host: biostudy-dev-mq.ebi.ac.uk
    username: manager
    password: manager-dev
    port: 5673

app:
  basepath: /ebi/teams/biostudies/backend/development
  submissionPath: /ebi/teams/biostudies/backend/development/submission
  ftpPath: /ebi/teams/biostudies/backend/development/submission/ftp
  tempDirPath: /ebi/teams/biostudies/backend/development/temp
  instanceBaseUrl: http://biostudy-bia.ebi.ac.uk:8788
  fire:
    host: # FIRE host
    username: # FIRE user
    password: # FIRE password
  security:
    environment: DEV
    tokenHash: D3V-3NV1R0NM3NT
    filesDirPath: /ebi/teams/biostudies/backend/development/dropbox
    magicDirPath: /ebi/teams/biostudies/backend/development/usergroup/Users
    requireActivation: false
    checkCaptcha: true
    captchaKey: 6Lc8JN0UAAAAADghgTRRo8D0jQUUDGr4va9VynWC
