spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  boot:
    admin:
      client:
        enabled: false

  data:
    mongodb:
      database: # Mongo Database Name
      uri: # Mongo Database connection URL

  datasource:
    url: # MySQL Database connection URL
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: # RabbitMQ host
    username: # RabbitMQ user
    password: # RabbitMQ password
    port: # RabbitMQ port
    listener:
      direct:
        prefetch: 25
      simple:
        prefetch: 25

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
      location: ${app.tempDirPath}

server:
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB


logging:
  file:
    name: logs/application_logs.txt
  level:
    org.springframework.data.mongodb.core.convert.QueryMapper: ERROR # Disable to avoid mapping log population.

app:
  consumers: 10 # number of processing queue consumers.
  maxConsumers: 15 # Max number of processing queue consumers.
  submissionPath: # Absolute path to the folder to be used as submission storage
  ftpPath: # Absolute path to the folder to be used ftp hardlinks
  tempDirPath: # Absolute path of the temp folder to store files
  requestFilesPath: # Base directory absolute path where request file list are stored.
  fireTempDirPath: # Absolute path of the temp folder for FIRE storage
  instanceBaseUrl: # Instance base url e.g. http://server.ebi.ac.uk:5541
#  subBasePath: # If present, it will be used as a prefix of submission relative path. Allows to allocate submissions under different paths
  fire:
    host: # FIRE host
    username: # FIRE user
    password: # FIRE password
    version: v1.1
    retry:
      maxAttempts: 20
      initialInterval: 100
      multiplier: 2.0
      maxInterval: 120
  security:
    captchaKey: # Captcha validation token
    checkCaptcha: false
    tokenHash: # Token used for hash authentication
    filesDirPath: # Absolute path to the folder to be used for the user/groups files
    magicDirPath: #  Absolute path to create user magic folder for dropbox simple access
    environment: # Current application execution environment
    requireActivation: # Indicates whether a new user need activation before being used
    instanceKeys:
      dev: # Instance key for the submission tool DEV environment
      beta: # Instance key for the submission tool BETA environment
      prod: # Instance key for the submission tool PROD environment
  persistence:
    enableFire: true
  mongo:
    execute-migrations: true
    migration-package: ac.uk.ebi.biostd.persistence.doc.migrations
  validator:
    euToxRiskValidationApi: # EU-ToxRisk validation API
  enablePropertiesLog: true
