spring:
  boot:
    admin:
      client:
        url: http://biostudy-prod.ebi.ac.uk:8590
        enabled: false
  datasource:
    url: # Database connection URL
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
      location: ${app.tempDirPath}

logging.file: logs/application_logs.txt
logging:
  file:
    max-history: 7

app:
  basepath: # Absolute path to the folder to be used as storage
  tempDirPath: # Absolute of the temp folder to store files
  security:
    tokenHash: # Token used for hash authentication
    filesDirPath: # Absolute path to the folder to be used for the user/groups files
    environment: # Current application execution environment
    requireActivation: # Indicates whether or not, new user need activation before being used
  notifications:
    smtp: smtp.ebi.ac.uk
    submissionNotification: # Indicates whether or not the user should be notified by email after a submission
