spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  boot:
    admin:
      client:
        url: http://biostudy-prod.ebi.ac.uk:8590
        enabled: false

  data:
    mongodb:
      database: BioStudiesMongo
      uri: mongodb://localhost:27017/BioStudiesMongo

  datasource:
    url: jdbc:mysql://localhost:3306/BioStudies?useSSL=false
    username: miguel
    password: mysql123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
      location: ${app.tempDirPath}

logging:
  file:
    max-history: 7
    name: /home/miguel1/Systems/Bio-Local/logs/application_logs.txt

app:
  submissionPath: /home/miguel1/Systems/Bio-Local/submissions
  ftpPath: /home/miguel1/Systems/Bio-Local/ftp
  tempDirPath: /home/miguel1/Systems/Bio-Local/temp
  instanceBaseUrl: http://localhost:8080
  fire:
    host: # FIRE host
    username: # FIRE user
    password: # FIRE password
  security:
    captchaKey: # Captcha validation token
    checkCaptcha: false
    tokenHash: 123-4-567
    filesDirPath: /home/miguel1/Systems/Bio-Local/files
    magicDirPath: /home/miguel1/Systems/Bio-Local/links
    environment: DEV
    requireActivation: false
  persistence:
    enableMongo: true
  mongo:
    execute-migrations: true
    migration-package: ac.uk.ebi.biostd.persistence.doc.migrations
  validator:
    euToxRiskValidationApi: # EU-ToxRisk validation API
