app:
  data:
    mode: PROCESS #SUBMIT #PROCESS #LOAD
    path: /home/jcamilorada/Desktop/PMC/2018-DUMP-SIMPLE/
    temp: /home/jcamilorada/Desktop/PMC/FILES
    mongodb-uri: mongodb://eubioimag:eNZJYfskIdw@mongodb-hx-eubioimagdev-001.ebi.ac.uk:27017,mongodb-hx-eubioimagdev-001.ebi.ac.uk:27017/eubioimag?replicaSet=eubioimagdevrs026&authSource=admin&waitQueueMultiple=100
    bio-studies-url: http://biostudy-bia.ebi.ac.uk:8689
    bio-studies-user: admin_user@ebi.ac.uk
    bio-studies-password: 123456
