spring:
  datasource:
    username: biostd
    password: biostd
    url: jdbc:mysql://mysql-fg-biostudy.ebi.ac.uk:4469/biostd_beta

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


app:
  basePath: /home/jcamilorada/Projects/BioStudies/NFS
