spring:
  datasource:
    url: jdbc:mysql://mysql-fg-biostudy-dev.ebi.ac.uk:4639/biostd_dev
    username: biostd_dev
    password: biostd_dev
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: biostudy-dev-mq.ebi.ac.uk
    port: 5673
    username: manager
    password: manager-dev

app:
  notifications:
    smtp: smtp.ebi.ac.uk
    uiUrl: http://ribs.ebi.ac.uk:8080/biostudies
    rt:
      host: https://testdesk.ebi.ac.uk
      queue: biostudies-testdesk
      user: biostudies-api
      password: biostudiestestpassword!2
