spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration

  datasource:
    url: # Database connection URL
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  rabbitmq:
    host: # RabbitMQ host
    username: # RabbitMQ user
    password: # RabbitMQ password


logging:
  file:
    path: logs
  logback:
    rollingpolicy:
      file-name-pattern: logs/start_logs.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 100MB

app:
  notifications:
    smtp: smtp.ebi.ac.uk
    uiUrl: # The BioStudies UI url
    stUrl: # The BioStudies ST url
    slackUrl: # Slack notifications URL
    # bccEmail: Nullable, optional email to include in every notification.
    rt:
      host: # RT server host
      queue: # Queue used for RT notifications
      user: # RT user
      password: # RT password
