app:
  fileName: # PMC links file name
  outputPath: # PMC links output path

  ftp:
    host: # FTP host to publish the PMC links
    user: # FTP user to publish the PMC links
    password: # FTP password to publish the PMC links
    port: # FTP port to publish the PMC links
