app:
  apps-folder: # Folder where app jar can be located
  notificationsUrl: # Slack notifications URL

  daily-scheduling:
    pmc: # Indicate whether or not the PMC related tasks should be daily triggered
    releaer: # Indicate whether or not the Submission Releaser related tasks should be daily triggered

  ssh:
    user: # ssh user
    password: # ssh user password
    server:  ## ssh sever (to submit jobs from)

pmc:
  import:
    temp: # Temporary folder to place PMC imported files
    mongoUri: # URI to mongo database used by the PMC import process

releaser:
  bioStudies:
    url: # BioStudies backend URL
    user: # BioStudies manager user
    password: # BioStudies manager password

  rabbitmq:
    host: # RabbitMQ Host
    user: # RabbitMQ User
    password: # RabbitMQ Password
    port: # RabbitMQ Port

  notification-times:
    first-warning-days: # Number of days before hand for the first warning to the users about upcoming release
    second-warning-days: # Number of days before hand for the second warning to the users about upcoming release
    third-warning-days: # Number of days before hand for the third warning to the users about upcoming release

spring:
  application:
    name: Scheduler Prod
  boot:
    admin:
      client:
        url: http://biostudy-prod.ebi.ac.uk:8590
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false
