app:
  apps-folder: # Folder where app jar can be located

  ssh:
    user: # ssh user
    password: # ssh user password
    server:  ## ssh sever (to submit jobs from)

pmc:
  import:
    temp:
    mongoUri:

spring:
  boot:
    admin:
      client:
        url: http://biostudy-prod.ebi.ac.uk:9545

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true

