app:
  apps-folder: # Folder where app jar can be located
  slack:
    pmcNotificationsUrl: # E-PMC Slack notifications URL
    schedulerNotificationsUrl:  # Scheduler Slack notifications URL

  daily-scheduling:
    pmc-import: # Indicates whether the PMC import pipeline be daily triggered
    pmc-export: # Indicates whether the PMC links export should be daily triggered
    notifier: # Indicates whether the Submission Release Notifier should be daily triggered
    releaser: # Indicates whether the Submission Releaser should be daily triggered
    exporter: # Indicates whether the Exporter should be daily triggered
    statsReporter: # Indicates whether the Stats Reporter task should be triggered

  cluster:
    user: # cluster ssh user
    sshKey: # cluster ssh key path.
    sshServer:  # cluster sever (to submit jobs from)
    logsPath: # path to place the logs of the dispatched jobs

pmc:
  import:
    temp: # Temporary folder to place PMC imported files
    mongoUri: # URI to mongo database used by the PMC import process
    loadFolder: # Folder to load .gz pmc files from

exporter:
  tmpFilesPath: # Path to the temp folder to store files
  publicOnly:
    fileName: # Name of the export file
    outputPath: # Path where the export file should be placed

  pmc:
    fileName: # PMC links file name
    outputPath: # PMC links output path

  ftp:
    host: # FTP host to publish the PMC links
    user: # FTP user to publish the PMC links
    password: # FTP password to publish the PMC links
    port: # FTP port to publish the PMC links

  persistence:
    database: # The database name to access the data
    uri: # The database connection URI

  bioStudies:
    url: # BioStudies backend URL
    user: # BioStudies manager user
    password: # BioStudies manager password

releaser:
  bioStudies:
    url: # BioStudies backend URL
    user: # BioStudies manager user
    password: # BioStudies manager password

  persistence:
    database: # The name of the database to access the data
    uri: # The database connection URI

  rabbitmq:
    host: # RabbitMQ Host
    user: # RabbitMQ User
    password: # RabbitMQ Password
    port: # RabbitMQ Port

  notification-times:
    first-warning-days: # Number of days beforehand for the first warning to the users about upcoming release
    second-warning-days: # Number of days beforehand for the second warning to the users about upcoming release
    third-warning-days: # Number of days beforehand for the third warning to the users about upcoming release

stats:
  publishPath: # Path where the stats report files should be published
  persistence:
    database: # The name of the database to access the data
    uri: # The database connection URI

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false
