spring:
  datasource:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
app:
  basepath: {BASE_PATH}
  environment: TEST
  security:
    tokenHash: biostd-test
    requireActivation: false
