openapi: 3.0.0
info:
  title: BioStudies API
  description:
    In order to facilitate some of the tasks that we need to perform such as refreshing a submission or generating FTP
    links, we've created some endpoints that are intended only for internal usage.
  version: 1.0.0
servers:
  - url: 'http://biostudy-prod.ebi.ac.uk:8788'
    description: PROD
  - url: 'http://biostudy-dev.ebi.ac.uk:8788'
    description: BETA
  - url: 'http://biostudy-bia.ebi.ac.uk:8788'
    description: DEV

tags:
  - name: Security
  - name: Extended Submissions
  - name: Refresh
  - name: Submission Drafts
  - name: FTP
  - name: Submission Releaser
  - name: PMC Importer

paths:
  /auth/register:
    $ref: 'security/RegisterUser.yaml'
  /auth/activate/{activationKey}:
    $ref: 'security/ActivateUser.yaml'
  /auth/check-registration:
    $ref: 'security/CheckUserRegistration.yaml'
  /auth/retryact:
    $ref: 'security/RetryUserActivation.yaml'
  /auth/refresh-user:
    $ref: 'security/RefreshUser.yaml'

  /submissions/refresh/{accNo}:
    $ref: 'submissions/operations/RefreshSubmission.yaml'
  /submissions/extended:
    $ref: 'submissions/extended/ExtSubmissionOperations.yaml'
  /submissions/extended/{accNo}:
    $ref: 'submissions/extended/GetExtSubmission.yaml'

