spring:
  data:
    mongodb:
      database: # The name of the database to access the data
      uri: # The database connection URI

  rabbitmq:
    host: # RabbitMQ Host
    username: # RabbitMQ User
    password: # RabbitMQ Password
    port: # RabbitMQ Port
  main:
    web-application-type: none

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

app:
  mode: # Releaser mode: RELEASE, NOTIFY, GENERATE_FTP_LINKS
  bioStudies:
    url: # BioStudies backend URL
    user: # BioStudies manager user
    password: # BioStudies manager password

  notification-times:
    first-warning-days: # Number of days beforehand for the first warning to the users about upcoming release
    second-warning-days: # Number of days beforehand for the second warning to the users about upcoming release
    third-warning-days: # Number of days beforehand for the third warning to the users about upcoming release
